const Ziggy = {
    "url": "http:\/\/www.teamworx.local", "port": null, "defaults": {}, "routes": {
        "debugbar.openhandler": {"uri": "_debugbar\/open", "methods": ["GET", "HEAD"]},
        "debugbar.clockwork": {"uri": "_debugbar\/clockwork\/{id}", "methods": ["GET", "HEAD"]},
        "debugbar.assets.css": {"uri": "_debugbar\/assets\/stylesheets", "methods": ["GET", "HEAD"]},
        "debugbar.assets.js": {"uri": "_debugbar\/assets\/javascript", "methods": ["GET", "HEAD"]},
        "debugbar.cache.delete": {"uri": "_debugbar\/cache\/{key}\/{tags?}", "methods": ["DELETE"]},
        "getFilteredGoodsflowItems": {"uri": "api\/getFilteredGoodsflowItems", "methods": ["GET", "HEAD"]},
        "set_language": {"uri": "set_language\/{language}", "methods": ["GET", "HEAD"]},
        "welcome": {"uri": "\/", "methods": ["GET", "HEAD"]},
        "login": {"uri": "login", "methods": ["GET", "HEAD"]},
        "logout": {"uri": "logout", "methods": ["POST"]},
        "password.request": {"uri": "password\/reset", "methods": ["GET", "HEAD"]},
        "password.email": {"uri": "password\/email", "methods": ["POST"]},
        "password.reset": {"uri": "password\/reset\/{token}", "methods": ["GET", "HEAD"]},
        "password.update": {"uri": "password\/reset", "methods": ["POST"]},
        "password.confirm": {"uri": "password\/confirm", "methods": ["GET", "HEAD"]},
        "home": {"uri": "home", "methods": ["GET", "HEAD"]},
        "test": {"uri": "test", "methods": ["GET", "HEAD"]},
        "lists": {"uri": "lists", "methods": ["GET", "HEAD"]},
        "goodsFlowItemFilterView": {"uri": "goodsFlowItemFilterView", "methods": ["GET", "HEAD"]},
        "RAZERBatteryGoodBad": {"uri": "RAZERBatteryGoodBad", "methods": ["GET", "HEAD"]},
        "RAZERBatteryGoodBadDownload": {"uri": "RAZERBatteryGoodBadDownload", "methods": ["GET", "HEAD"]},
        "RAZERBatteryGoodBadUpload": {"uri": "RAZERBatteryGoodBadUpload", "methods": ["POST"]},
        "RAZERBatteryGoodBadAddConfirmation": {"uri": "RAZERBatteryGoodBadAddConfirmation", "methods": ["POST"]},
        "RAZERBatteryGoodBadAdd": {"uri": "RAZERBatteryGoodBadAdd", "methods": ["POST"]},
        "RAZERBatteryGoodBadEditSearch": {"uri": "RAZERBatteryGoodBadEditSearch", "methods": ["POST"]},
        "RAZERBatteryGoodBadEditRZSelected": {"uri": "RAZERBatteryGoodBadEditRZSelected", "methods": ["POST"]},
        "RAZERBatteryGoodBadSubmitEditedRZ": {"uri": "RAZERBatteryGoodBadSubmitEditedRZ", "methods": ["POST"]},
        "RAZERBatteryGoodBadSubmitRZForDelete": {"uri": "RAZERBatteryGoodBadSubmitRZForDelete", "methods": ["POST"]},
        "calculatorView": {"uri": "calculator", "methods": ["GET", "HEAD"]},
        "boxSearch": {"uri": "boxSearch\/{searchString}", "methods": ["GET", "HEAD"]},
        "box": {"uri": "box\/{id}", "methods": ["GET", "HEAD"]},
        "boxLabel": {"uri": "print\/boxLabel\/{boxId}\/{count}", "methods": ["GET", "HEAD"]},
        "boxScan": {"uri": "scan\/box\/{id}", "methods": ["GET", "HEAD"]},
        "submitGf": {"uri": "scan\/submitGf", "methods": ["POST"]},
        "getScannedGfIds": {"uri": "scan\/getScannedGfIds", "methods": ["POST"]},
        "createBoxScan": {"uri": "scan\/createBoxScan", "methods": ["POST"]},
        "getOpenScanIdForBox": {"uri": "scan\/getOpenScanIdForBox", "methods": ["POST"]},
        "getNeedToScanGFIds": {"uri": "scan\/getNeedToScanGFIds", "methods": ["POST"]},
        "getClosedScansForBox": {"uri": "scan\/getClosedScansForBox", "methods": ["POST"]},
        "closeScan": {"uri": "scan\/closeScan", "methods": ["POST"]},
        "newItemScan": {"uri": "newItemScan", "methods": ["GET", "HEAD"]},
        "createNewItemScan": {"uri": "createNewItemScan", "methods": ["POST"]},
        "createNewEmptyItemScan": {"uri": "createNewEmptyItemScan", "methods": ["POST"]},
        "getNewScans": {"uri": "getNewScans", "methods": ["GET", "HEAD"]},
        "getDoneScans": {"uri": "getDoneScans", "methods": ["GET", "HEAD"]},
        "getConfirmedScans": {"uri": "getConfirmedScans", "methods": ["GET", "HEAD"]},
        "GoToScan": {"uri": "scan\/{id}", "methods": ["GET", "HEAD"]},
        "getNeedToScanSNs": {"uri": "getNeedToScanSNs", "methods": ["GET", "HEAD"]},
        "getScannedSNs": {"uri": "getScannedSNs", "methods": ["GET", "HEAD"]},
        "getRegularPallets": {"uri": "getRegularPallets", "methods": ["GET", "HEAD"]},
        "getDifferences": {"uri": "getDifferences", "methods": ["GET", "HEAD"]},
        "closePallet": {"uri": "closePallet", "methods": ["GET", "HEAD"]},
        "makeScanDone": {"uri": "makeScanDone", "methods": ["POST"]},
        "makeScanNew": {"uri": "makeScanNew", "methods": ["POST"]},
        "makeScanConfirmed": {"uri": "makeScanConfirmed", "methods": ["POST"]},
        "generateXlsx": {"uri": "generateXlsx", "methods": ["POST"]},
        "deleteXlsxFile": {"uri": "deleteXlsxFile", "methods": ["POST"]},
        "downloadXlsxFile": {"uri": "downloadXlsxFile\/{id}", "methods": ["GET", "HEAD"]},
        "getScanData": {"uri": "getScanData", "methods": ["GET", "HEAD"]},
        "checkIfFileExists": {"uri": "checkIfFileExists", "methods": ["POST"]},
        "rewritePalletNumbers": {"uri": "rewritePalletNumbers", "methods": ["GET", "HEAD"]},
        "openPallet": {"uri": "openPallet", "methods": ["GET", "HEAD"]},
        "deletePallet": {"uri": "deletePallet", "methods": ["GET", "HEAD"]},
        "getResults": {"uri": "getResults", "methods": ["GET", "HEAD"]},
        "createRequiredListAudioFiles": {"uri": "createRequiredListAudioFiles", "methods": ["POST"]},
        "SNSubmit": {"uri": "SNSubmit", "methods": ["POST"]},
        "SNEanSubmit": {"uri": "SNEanSubmit", "methods": ["POST"]},
        "multipleNoSnSubmit": {"uri": "multipleNoSnSubmit", "methods": ["POST"]},
        "scannedSnEdit": {"uri": "scannedSnEdit", "methods": ["POST"]},
        "deleteScannedProduct": {"uri": "deleteScannedProduct", "methods": ["POST"]},
        "deleteScannedItems": {"uri": "deleteScannedItems", "methods": ["POST"]},
        "getRazerAPIStatus": {"uri": "getRazerAPIStatus", "methods": ["GET", "HEAD"]},
        "getRequiredListUsageStatus": {"uri": "getRequiredListUsageStatus", "methods": ["GET", "HEAD"]},
        "toggleRazerAPIStatus": {"uri": "toggleRazerAPIStatus", "methods": ["GET", "HEAD"]},
        "toggleRequiredListUsageStatus": {"uri": "toggleRequiredListUsageStatus", "methods": ["GET", "HEAD"]},
        "searchProductIdForScan": {"uri": "searchProductIdForScan", "methods": ["POST"]},
        "getVoiceList": {"uri": "getVoiceList", "methods": ["GET", "HEAD"]},
        "getUsersVoiceSettings": {"uri": "getUsersVoiceSettings", "methods": ["GET", "HEAD"]},
        "changeUsersVoiceSettings": {"uri": "changeUsersVoiceSettings", "methods": ["POST"]},
        "checkIfTestAudioExists": {"uri": "checkIfTestAudioExists", "methods": ["GET", "HEAD"]},
        "requiredList": {"uri": "requiredList", "methods": ["GET", "HEAD"]},
        "requiredListUpload": {"uri": "requiredListUpload", "methods": ["POST"]},
        "getActiveRequiredLists": {"uri": "getActiveRequiredLists", "methods": ["GET", "HEAD"]},
        "getActiveRequiredListIds": {"uri": "getActiveRequiredListIds", "methods": ["GET", "HEAD"]},
        "getDisabledRequiredLists": {"uri": "getDisabledRequiredLists", "methods": ["GET", "HEAD"]},
        "closeRequiredPallet": {"uri": "closeRequiredPallet", "methods": ["POST"]},
        "downloadRequiredPalletXlsx": {"uri": "downloadRequiredPalletXlsx\/{id}", "methods": ["GET", "HEAD"]},
        "openRequiredPallet": {"uri": "openRequiredPallet", "methods": ["POST"]},
        "deleteRequiredPallet": {"uri": "deleteRequiredPallet", "methods": ["POST"]},
        "getSelectedListPallets": {"uri": "getSelectedListPallets", "methods": ["POST"]},
        "savePriorities": {"uri": "savePriorities", "methods": ["POST"]},
        "selectRequiredListToDisplay": {"uri": "selectRequiredListToDisplay", "methods": ["POST"]},
        "editRequiredListQuantity": {"uri": "editRequiredListQuantity", "methods": ["POST"]},
        "deleteRequiredListProduct": {"uri": "deleteRequiredListProduct", "methods": ["POST"]},
        "deleteRequiredListProducts": {"uri": "deleteRequiredListProducts", "methods": ["POST"]},
        "RequiredListAddNewProduct": {"uri": "RequiredListAddNewProduct", "methods": ["POST"]},
        "editRequiredList": {"uri": "editRequiredList", "methods": ["POST"]},
        "createNewEmptyList": {"uri": "createNewEmptyList", "methods": ["POST"]},
        "getNewItemScanLockStatus": {"uri": "getNewItemScanLockStatus", "methods": ["GET", "HEAD"]},
        "lockNewItemScan": {"uri": "lockNewItemScan", "methods": ["GET", "HEAD"]},
        "unlockNewItemScan": {"uri": "unlockNewItemScan", "methods": ["GET", "HEAD"]},
        "deactivateRequiredList": {"uri": "deactivateRequiredList", "methods": ["POST"]},
        "activateRequiredList": {"uri": "activateRequiredList", "methods": ["POST"]},
        "getRequiredListActivityStatus": {"uri": "getRequiredListActivityStatus", "methods": ["POST"]},
        "deleteRequiredList": {"uri": "deleteRequiredList", "methods": ["POST"]},
        "sendRegisterInvitation": {"uri": "sendRegisterInvitation", "methods": ["POST"]},
        "finishRegistration": {"uri": "finishRegistration", "methods": ["POST"]},
        "registerWithInvitation": {"uri": "registerWithInvitation\/{token}", "methods": ["GET", "HEAD"]},
        "adminPanel": {"uri": "adminPanel", "methods": ["GET", "HEAD"]},
        "setGatePhoneNumber": {"uri": "setGatePhoneNumber", "methods": ["POST"]},
        "deleteGatePhoneNumber": {"uri": "deleteGatePhoneNumber", "methods": ["GET", "HEAD"]},
        "getGatePhoneNumber": {"uri": "getGatePhoneNumber", "methods": ["GET", "HEAD"]},
        "searchUserForPrivilegeEdit": {"uri": "searchUserForPrivilegeEdit", "methods": ["POST"]},
        "getPrivilegeSetsForUser": {"uri": "getPrivilegeSetsForUser", "methods": ["POST"]},
        "removePrivilege": {"uri": "removePrivilege", "methods": ["POST"]},
        "addPrivilege": {"uri": "addPrivilege", "methods": ["POST"]},
        "boxBuildMenu": {"uri": "boxBuildMenu", "methods": ["GET", "HEAD"]},
        "boxBuildMaker": {"uri": "boxBuildMaker", "methods": ["GET", "HEAD"]},
        "createBoxBuild": {"uri": "createBoxBuild", "methods": ["POST"]},
        "addNewWarehouseCenter": {"uri": "addNewWarehouseCenter", "methods": ["POST"]},
        "getAllWarehouseCenters": {"uri": "getAllWarehouseCenters", "methods": ["GET", "HEAD"]},
        "getSelectedWarehouseData": {"uri": "getSelectedWarehouseData", "methods": ["POST"]},
        "editWarehouseCenter": {"uri": "editWarehouseCenter", "methods": ["POST"]},
        "deleteWarehouseCenter": {"uri": "deleteWarehouseCenter", "methods": ["POST"]},
        "getAllBoxBuilds": {"uri": "getAllBoxBuilds", "methods": ["POST"]},
        "activateBoxBuild": {"uri": "activateBoxBuild", "methods": ["POST"]},
        "deActivateBoxBuild": {"uri": "deActivateBoxBuild", "methods": ["POST"]},
        "boxBuildViewer": {"uri": "boxBuildViewer\/{id}", "methods": ["GET", "HEAD"]},
        "boxBuildList": {"uri": "boxBuildList", "methods": ["GET", "HEAD"]},
        "getBoxBuildRequiredItems": {"uri": "getBoxBuildRequiredItems\/{id}", "methods": ["GET", "HEAD"]},
        "getBoxBuildViewerBoxes": {"uri": "getBoxBuildViewerBoxes", "methods": ["POST"]},
        "searchForPalletIds": {"uri": "searchForPalletIds", "methods": ["POST"]},
        "boxBuildFindItems": {"uri": "boxBuildFindItems", "methods": ["POST"]},
        "getNeedToFindAmountsByManufacturer": {"uri": "getNeedToFindAmountsByManufacturer", "methods": ["POST"]},
        "deleteItemFromBoxBuildList": {"uri": "deleteItemFromBoxBuildList", "methods": ["POST"]},
        "editBoxBuildItem": {"uri": "editBoxBuildItem", "methods": ["POST"]},
        "boxBuildScan": {"uri": "boxBuildScan", "methods": ["GET", "HEAD"]},
        "boxBuildSubmitGoodsFlowId": {"uri": "boxBuildSubmitGoodsFlowId", "methods": ["POST"]},
        "setDirectScanFulfilmentCenter": {"uri": "setDirectScanFulfilmentCenter", "methods": ["POST"]},
        "getFulfilmentCenters": {"uri": "getFulfilmentCenters", "methods": ["GET", "HEAD"]},
        "getDirectScanFulfilmentCenter": {"uri": "getDirectScanFulfilmentCenter", "methods": ["GET", "HEAD"]},
        "getDirectScanStatus": {"uri": "getDirectScanStatus", "methods": ["GET", "HEAD"]},
        "toggleDirectScanStatus": {"uri": "toggleDirectScanStatus", "methods": ["GET", "HEAD"]},
        "prepareBoxBuildAudioFiles": {"uri": "prepareBoxBuildAudioFiles", "methods": ["GET", "HEAD"]},
        "getOpenBoxBuildBoxes": {"uri": "getOpenBoxBuildBoxes", "methods": ["GET", "HEAD"]},
        "deleteBoxBuildBoxItem": {"uri": "deleteBoxBuildBoxItem", "methods": ["POST"]},
        "deleteBoxBuildBox": {"uri": "deleteBoxBuildBox", "methods": ["POST"]},
        "closeBoxBuildBox": {"uri": "closeBoxBuildBox", "methods": ["POST"]},
        "boxBuildLabel": {"uri": "boxBuildLabel\/{id}", "methods": ["GET", "HEAD"]},
        "sendContactUsMessage": {"uri": "SendContactUsMessage", "methods": ["POST"]},
        "itemTransfer": {"uri": "itemTransfer", "methods": ["GET", "HEAD"]},
        "itemTransferSearchForBox": {"uri": "itemTransferSearchForBox", "methods": ["POST"]},
        "transferItems": {"uri": "transferItems", "methods": ["POST"]},
        "gateOpener": {"uri": "gateOpener", "methods": ["GET", "HEAD"]},
        "makeCallToGates": {"uri": "makeCallToGates", "methods": ["POST"]},
        "gatesCallback": {
            "uri": "gatesCallback\/rth87k4uil15632v1df9847894ikl156g1fQW941G8K41UIG98L6",
            "methods": ["POST"]
        }
    }
};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export {Ziggy};
